package com.smt.bj.strategy;

import static com.smt.bj.house.Hand.*;
import static com.smt.bj.strategy.Action.*;

import com.google.common.collect.ImmutableMap;
import com.smt.bj.house.Hand;
import com.smt.bj.house.HouseRule;

public class BasicStrategyLookUpTable {
    
    private static final ImmutableMap<Key, Action[]> ACTION_TABLE = ImmutableMap.<Key, Action[]>builder()
            //pair
            .put(new Key(PAIR_A, 1), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 2), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 3), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 4), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 5), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 6), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 7), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 8), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 9), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_A, 10), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 1), new Action[]{HIT})
            .put(new Key(PAIR_2, 2), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 3), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 4), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 5), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 6), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 7), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_2, 8), new Action[]{HIT})
            .put(new Key(PAIR_2, 9), new Action[]{HIT})
            .put(new Key(PAIR_2, 10), new Action[]{HIT})
            .put(new Key(PAIR_3, 1), new Action[]{HIT})
            .put(new Key(PAIR_3, 2), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 3), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 4), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 5), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 6), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 7), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_3, 8), new Action[]{HIT})
            .put(new Key(PAIR_3, 9), new Action[]{HIT})
            .put(new Key(PAIR_3, 10), new Action[]{HIT})
            .put(new Key(PAIR_4, 1), new Action[]{HIT})
            .put(new Key(PAIR_4, 2), new Action[]{HIT})
            .put(new Key(PAIR_4, 3), new Action[]{HIT})
            .put(new Key(PAIR_4, 4), new Action[]{HIT})
            .put(new Key(PAIR_4, 5), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_4, 6), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_4, 7), new Action[]{HIT})
            .put(new Key(PAIR_4, 8), new Action[]{HIT})
            .put(new Key(PAIR_4, 9), new Action[]{HIT})
            .put(new Key(PAIR_4, 10), new Action[]{HIT})
            .put(new Key(PAIR_5, 1), new Action[]{HIT})
            .put(new Key(PAIR_5, 2), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 3), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 7), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 8), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 9), new Action[]{DOUBLE, HIT})
            .put(new Key(PAIR_5, 10), new Action[]{HIT})
            .put(new Key(PAIR_6, 1), new Action[]{HIT})
            .put(new Key(PAIR_6, 2), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_6, 3), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_6, 4), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_6, 5), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_6, 6), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_6, 7), new Action[]{HIT})
            .put(new Key(PAIR_6, 8), new Action[]{HIT})
            .put(new Key(PAIR_6, 9), new Action[]{HIT})
            .put(new Key(PAIR_6, 10), new Action[]{HIT})
            .put(new Key(PAIR_7, 1), new Action[]{HIT})
            .put(new Key(PAIR_7, 2), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_7, 3), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_7, 4), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_7, 5), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_7, 6), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_7, 7), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_7, 8), new Action[]{HIT})
            .put(new Key(PAIR_7, 9), new Action[]{HIT})
            .put(new Key(PAIR_7, 10), new Action[]{HIT})
            .put(new Key(PAIR_8, 1), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_8, 2), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_8, 3), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_8, 4), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_8, 5), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_8, 6), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_8, 7), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_8, 8), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_8, 9), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_8, 10), new Action[]{SPLIT, HIT})
            .put(new Key(PAIR_9, 1), new Action[]{STAND})
            .put(new Key(PAIR_9, 2), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 3), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 4), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 5), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 6), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 7), new Action[]{STAND})
            .put(new Key(PAIR_9, 8), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 9), new Action[]{SPLIT, STAND})
            .put(new Key(PAIR_9, 10), new Action[]{STAND})
            .put(new Key(PAIR_10, 1), new Action[]{STAND})
            .put(new Key(PAIR_10, 2), new Action[]{STAND})
            .put(new Key(PAIR_10, 3), new Action[]{STAND})
            .put(new Key(PAIR_10, 4), new Action[]{STAND})
            .put(new Key(PAIR_10, 5), new Action[]{STAND})
            .put(new Key(PAIR_10, 6), new Action[]{STAND})
            .put(new Key(PAIR_10, 7), new Action[]{STAND})
            .put(new Key(PAIR_10, 8), new Action[]{STAND})
            .put(new Key(PAIR_10, 9), new Action[]{STAND})
            .put(new Key(PAIR_10, 10), new Action[]{STAND})
            //Hard total
            .put(new Key(HARD_5, 1), new Action[]{HIT})
            .put(new Key(HARD_5, 2), new Action[]{HIT})
            .put(new Key(HARD_5, 3), new Action[]{HIT})
            .put(new Key(HARD_5, 4), new Action[]{HIT})
            .put(new Key(HARD_5, 5), new Action[]{HIT})
            .put(new Key(HARD_5, 6), new Action[]{HIT})
            .put(new Key(HARD_5, 7), new Action[]{HIT})
            .put(new Key(HARD_5, 8), new Action[]{HIT})
            .put(new Key(HARD_5, 9), new Action[]{HIT})
            .put(new Key(HARD_5, 10), new Action[]{HIT})
            .put(new Key(HARD_6, 1), new Action[]{HIT})
            .put(new Key(HARD_6, 2), new Action[]{HIT})
            .put(new Key(HARD_6, 3), new Action[]{HIT})
            .put(new Key(HARD_6, 4), new Action[]{HIT})
            .put(new Key(HARD_6, 5), new Action[]{HIT})
            .put(new Key(HARD_6, 6), new Action[]{HIT})
            .put(new Key(HARD_6, 7), new Action[]{HIT})
            .put(new Key(HARD_6, 8), new Action[]{HIT})
            .put(new Key(HARD_6, 9), new Action[]{HIT})
            .put(new Key(HARD_6, 10), new Action[]{HIT})
            .put(new Key(HARD_7, 1), new Action[]{HIT})
            .put(new Key(HARD_7, 2), new Action[]{HIT})
            .put(new Key(HARD_7, 3), new Action[]{HIT})
            .put(new Key(HARD_7, 4), new Action[]{HIT})
            .put(new Key(HARD_7, 5), new Action[]{HIT})
            .put(new Key(HARD_7, 6), new Action[]{HIT})
            .put(new Key(HARD_7, 7), new Action[]{HIT})
            .put(new Key(HARD_7, 8), new Action[]{HIT})
            .put(new Key(HARD_7, 9), new Action[]{HIT})
            .put(new Key(HARD_7, 10), new Action[]{HIT})
            .put(new Key(HARD_8, 1), new Action[]{HIT})
            .put(new Key(HARD_8, 2), new Action[]{HIT})
            .put(new Key(HARD_8, 3), new Action[]{HIT})
            .put(new Key(HARD_8, 4), new Action[]{HIT})
            .put(new Key(HARD_8, 5), new Action[]{HIT})
            .put(new Key(HARD_8, 6), new Action[]{HIT})
            .put(new Key(HARD_8, 7), new Action[]{HIT})
            .put(new Key(HARD_8, 8), new Action[]{HIT})
            .put(new Key(HARD_8, 9), new Action[]{HIT})
            .put(new Key(HARD_8, 10), new Action[]{HIT})
            .put(new Key(HARD_9, 1), new Action[]{HIT})
            .put(new Key(HARD_9, 2), new Action[]{HIT})
            .put(new Key(HARD_9, 3), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_9, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_9, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_9, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_9, 7), new Action[]{HIT})
            .put(new Key(HARD_9, 8), new Action[]{HIT})
            .put(new Key(HARD_9, 9), new Action[]{HIT})
            .put(new Key(HARD_9, 10), new Action[]{HIT})
            .put(new Key(HARD_10, 1), new Action[]{HIT})
            .put(new Key(HARD_10, 2), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 3), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 7), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 8), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 9), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_10, 10), new Action[]{HIT})
            .put(new Key(HARD_11, 1), new Action[]{HIT})
            .put(new Key(HARD_11, 2), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 3), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 7), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 8), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 9), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_11, 10), new Action[]{DOUBLE, HIT})
            .put(new Key(HARD_12, 1), new Action[]{HIT})
            .put(new Key(HARD_12, 2), new Action[]{HIT})
            .put(new Key(HARD_12, 3), new Action[]{HIT})
            .put(new Key(HARD_12, 4), new Action[]{STAND})
            .put(new Key(HARD_12, 5), new Action[]{STAND})
            .put(new Key(HARD_12, 6), new Action[]{STAND})
            .put(new Key(HARD_12, 7), new Action[]{HIT})
            .put(new Key(HARD_12, 8), new Action[]{HIT})
            .put(new Key(HARD_12, 9), new Action[]{HIT})
            .put(new Key(HARD_12, 10), new Action[]{HIT})
            .put(new Key(HARD_13, 1), new Action[]{HIT})
            .put(new Key(HARD_13, 2), new Action[]{STAND})
            .put(new Key(HARD_13, 3), new Action[]{STAND})
            .put(new Key(HARD_13, 4), new Action[]{STAND})
            .put(new Key(HARD_13, 5), new Action[]{STAND})
            .put(new Key(HARD_13, 6), new Action[]{STAND})
            .put(new Key(HARD_13, 7), new Action[]{HIT})
            .put(new Key(HARD_13, 8), new Action[]{HIT})
            .put(new Key(HARD_13, 9), new Action[]{HIT})
            .put(new Key(HARD_13, 10), new Action[]{HIT})
            .put(new Key(HARD_14, 1), new Action[]{HIT})
            .put(new Key(HARD_14, 2), new Action[]{STAND})
            .put(new Key(HARD_14, 3), new Action[]{STAND})
            .put(new Key(HARD_14, 4), new Action[]{STAND})
            .put(new Key(HARD_14, 5), new Action[]{STAND})
            .put(new Key(HARD_14, 6), new Action[]{STAND})
            .put(new Key(HARD_14, 7), new Action[]{HIT})
            .put(new Key(HARD_14, 8), new Action[]{HIT})
            .put(new Key(HARD_14, 9), new Action[]{HIT})
            .put(new Key(HARD_14, 10), new Action[]{HIT})    
            .put(new Key(HARD_15, 1), new Action[]{HIT})
            .put(new Key(HARD_15, 2), new Action[]{STAND})
            .put(new Key(HARD_15, 3), new Action[]{STAND})
            .put(new Key(HARD_15, 4), new Action[]{STAND})
            .put(new Key(HARD_15, 5), new Action[]{STAND})
            .put(new Key(HARD_15, 6), new Action[]{STAND})
            .put(new Key(HARD_15, 7), new Action[]{HIT})
            .put(new Key(HARD_15, 8), new Action[]{HIT})
            .put(new Key(HARD_15, 9), new Action[]{HIT})
            .put(new Key(HARD_15, 10), new Action[]{SURRENDER, HIT})
            .put(new Key(HARD_16, 1), new Action[]{SURRENDER, HIT})
            .put(new Key(HARD_16, 2), new Action[]{STAND})
            .put(new Key(HARD_16, 3), new Action[]{STAND})
            .put(new Key(HARD_16, 4), new Action[]{STAND})
            .put(new Key(HARD_16, 5), new Action[]{STAND})
            .put(new Key(HARD_16, 6), new Action[]{STAND})
            .put(new Key(HARD_16, 7), new Action[]{HIT})
            .put(new Key(HARD_16, 8), new Action[]{HIT})
            .put(new Key(HARD_16, 9), new Action[]{SURRENDER, HIT})
            .put(new Key(HARD_16, 10), new Action[]{SURRENDER, HIT}) 
            .put(new Key(HARD_17, 1), new Action[]{STAND})
            .put(new Key(HARD_17, 2), new Action[]{STAND})
            .put(new Key(HARD_17, 3), new Action[]{STAND})
            .put(new Key(HARD_17, 4), new Action[]{STAND})
            .put(new Key(HARD_17, 5), new Action[]{STAND})
            .put(new Key(HARD_17, 6), new Action[]{STAND})
            .put(new Key(HARD_17, 7), new Action[]{STAND})
            .put(new Key(HARD_17, 8), new Action[]{STAND})
            .put(new Key(HARD_17, 9), new Action[]{STAND})
            .put(new Key(HARD_17, 10), new Action[]{STAND}) 
            .put(new Key(HARD_18, 1), new Action[]{STAND})
            .put(new Key(HARD_18, 2), new Action[]{STAND})
            .put(new Key(HARD_18, 3), new Action[]{STAND})
            .put(new Key(HARD_18, 4), new Action[]{STAND})
            .put(new Key(HARD_18, 5), new Action[]{STAND})
            .put(new Key(HARD_18, 6), new Action[]{STAND})
            .put(new Key(HARD_18, 7), new Action[]{STAND})
            .put(new Key(HARD_18, 8), new Action[]{STAND})
            .put(new Key(HARD_18, 9), new Action[]{STAND})
            .put(new Key(HARD_18, 10), new Action[]{STAND})   
            .put(new Key(HARD_19, 1), new Action[]{STAND})
            .put(new Key(HARD_19, 2), new Action[]{STAND})
            .put(new Key(HARD_19, 3), new Action[]{STAND})
            .put(new Key(HARD_19, 4), new Action[]{STAND})
            .put(new Key(HARD_19, 5), new Action[]{STAND})
            .put(new Key(HARD_19, 6), new Action[]{STAND})
            .put(new Key(HARD_19, 7), new Action[]{STAND})
            .put(new Key(HARD_19, 8), new Action[]{STAND})
            .put(new Key(HARD_19, 9), new Action[]{STAND})
            .put(new Key(HARD_19, 10), new Action[]{STAND}) 
            .put(new Key(HARD_20, 1), new Action[]{STAND})
            .put(new Key(HARD_20, 2), new Action[]{STAND})
            .put(new Key(HARD_20, 3), new Action[]{STAND})
            .put(new Key(HARD_20, 4), new Action[]{STAND})
            .put(new Key(HARD_20, 5), new Action[]{STAND})
            .put(new Key(HARD_20, 6), new Action[]{STAND})
            .put(new Key(HARD_20, 7), new Action[]{STAND})
            .put(new Key(HARD_20, 8), new Action[]{STAND})
            .put(new Key(HARD_20, 9), new Action[]{STAND})
            .put(new Key(HARD_20, 10), new Action[]{STAND})
            //Soft total
            .put(new Key(A2, 1), new Action[]{HIT})
            .put(new Key(A2, 2), new Action[]{HIT})
            .put(new Key(A2, 3), new Action[]{HIT})
            .put(new Key(A2, 4), new Action[]{HIT})
            .put(new Key(A2, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(A2, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(A2, 7), new Action[]{HIT})
            .put(new Key(A2, 8), new Action[]{HIT})
            .put(new Key(A2, 9), new Action[]{HIT})
            .put(new Key(A2, 10), new Action[]{HIT})
            .put(new Key(A3, 1), new Action[]{HIT})
            .put(new Key(A3, 2), new Action[]{HIT})
            .put(new Key(A3, 3), new Action[]{HIT})
            .put(new Key(A3, 4), new Action[]{HIT})
            .put(new Key(A3, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(A3, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(A3, 7), new Action[]{HIT})
            .put(new Key(A3, 8), new Action[]{HIT})
            .put(new Key(A3, 9), new Action[]{HIT})
            .put(new Key(A3, 10), new Action[]{HIT})
            .put(new Key(A4, 1), new Action[]{HIT})
            .put(new Key(A4, 2), new Action[]{HIT})
            .put(new Key(A4, 3), new Action[]{HIT})
            .put(new Key(A4, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(A4, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(A4, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(A4, 7), new Action[]{HIT})
            .put(new Key(A4, 8), new Action[]{HIT})
            .put(new Key(A4, 9), new Action[]{HIT})
            .put(new Key(A4, 10), new Action[]{HIT})
            .put(new Key(A5, 1), new Action[]{HIT})
            .put(new Key(A5, 2), new Action[]{HIT})
            .put(new Key(A5, 3), new Action[]{HIT})
            .put(new Key(A5, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(A5, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(A5, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(A5, 7), new Action[]{HIT})
            .put(new Key(A5, 8), new Action[]{HIT})
            .put(new Key(A5, 9), new Action[]{HIT})
            .put(new Key(A5, 10), new Action[]{HIT})
            .put(new Key(A6, 1), new Action[]{HIT})
            .put(new Key(A6, 2), new Action[]{HIT})
            .put(new Key(A6, 3), new Action[]{DOUBLE, HIT})
            .put(new Key(A6, 4), new Action[]{DOUBLE, HIT})
            .put(new Key(A6, 5), new Action[]{DOUBLE, HIT})
            .put(new Key(A6, 6), new Action[]{DOUBLE, HIT})
            .put(new Key(A6, 7), new Action[]{HIT})
            .put(new Key(A6, 8), new Action[]{HIT})
            .put(new Key(A6, 9), new Action[]{HIT})
            .put(new Key(A6, 10), new Action[]{HIT})
            .put(new Key(A7, 1), new Action[]{HIT})
            .put(new Key(A7, 2), new Action[]{STAND})
            .put(new Key(A7, 3), new Action[]{DOUBLE, STAND})
            .put(new Key(A7, 4), new Action[]{DOUBLE, STAND})
            .put(new Key(A7, 5), new Action[]{DOUBLE, STAND})
            .put(new Key(A7, 6), new Action[]{DOUBLE, STAND})
            .put(new Key(A7, 7), new Action[]{STAND})
            .put(new Key(A7, 8), new Action[]{STAND})
            .put(new Key(A7, 9), new Action[]{HIT})
            .put(new Key(A7, 10), new Action[]{HIT})            
            .put(new Key(A8, 1), new Action[]{STAND})
            .put(new Key(A8, 2), new Action[]{STAND})
            .put(new Key(A8, 3), new Action[]{STAND})
            .put(new Key(A8, 4), new Action[]{STAND})
            .put(new Key(A8, 5), new Action[]{STAND})
            .put(new Key(A8, 6), new Action[]{STAND})
            .put(new Key(A8, 7), new Action[]{STAND})
            .put(new Key(A8, 8), new Action[]{STAND})
            .put(new Key(A8, 9), new Action[]{STAND})
            .put(new Key(A8, 10), new Action[]{STAND})
            .put(new Key(A9, 1), new Action[]{STAND})
            .put(new Key(A9, 2), new Action[]{STAND})
            .put(new Key(A9, 3), new Action[]{STAND})
            .put(new Key(A9, 4), new Action[]{STAND})
            .put(new Key(A9, 5), new Action[]{STAND})
            .put(new Key(A9, 6), new Action[]{STAND})
            .put(new Key(A9, 7), new Action[]{STAND})
            .put(new Key(A9, 8), new Action[]{STAND})
            .put(new Key(A9, 9), new Action[]{STAND})
            .put(new Key(A9, 10), new Action[]{STAND})
            .build();
    
    public static Action findAction(Hand hand, int faceUpCard, HouseRule houseRule){
        Action[] actions = ACTION_TABLE.get(new Key(hand, faceUpCard));
        if (actions[0] == DOUBLE){
            return houseRule.allowDouble() ? DOUBLE : actions[1];
        }
        if (actions[0] == SPLIT){
            return houseRule.allowSplit() ? SPLIT : actions[1];
        }
        if (actions[0] == SURRENDER){
            return houseRule.allowSurrender() ? SURRENDER : actions[1];
        }
        return actions[0];
    }

}
